from flask import Flask, render_template, request, send_file
import subprocess
import os
import csv 

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/upload', methods=['POST'])
def upload_file():
    if 'file' not in request.files:
        return "No file part"
    
    file = request.files['file']

    if file.filename == '':
        return "No selected file"
    
    # Save the uploaded file to a temporary location
    file_path = 'D:/Personal Projects/tests/flask-cpp/' + file.filename
    file.save(file_path)

    # Run the C++ program using subprocess
    subprocess.run(['./application.exe', file_path])

    # Read the CSV file generated by the C++ program
    csv_file_path = 'D:/Personal Projects/tests/flask-cpp/Execution_rep.csv'

    print(csv_file_path)
    if os.path.exists(csv_file_path):
        # Read the content of the CSV file
        with open(csv_file_path, 'r') as csvfile:
            csv_content = list(csv.reader(csvfile))
            print(csv_content)
            
        # Render the template with the CSV content
        return render_template('execution_rep.html', csv_content=csv_content)
    else:
        return "CSV file not found"

if __name__ == '__main__':
    app.run(debug=True)